import { AppLayout } from "@/components/layout/AppLayout";
import { Card } from "@/components/ui/card";
import { Link } from "wouter";
import { ArrowLeft, Bot } from "lucide-react";

export default function AiDisclosure() {
  return (
    <AppLayout>
      <div className="p-4 flex flex-col gap-5">
        <Link href="/settings" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors w-fit pt-2">
          <ArrowLeft className="w-4 h-4" />
          Back to Settings
        </Link>

        <div className="flex items-center gap-3">
          <Bot className="w-5 h-5 text-primary" />
          <h1 className="text-2xl font-bold tracking-tight">AI Disclosure Policy</h1>
        </div>

        <Card className="p-4 bg-card border-border/50 flex flex-col gap-4 text-sm">

          <Section title="Artificial Intelligence Is Used in This Application">
            <p>Small Town Watchdog uses artificial intelligence (AI) to help citizens understand government documents. AI is used to generate plain-English summaries, ballot item explanations, year-over-year change descriptions, and risk indicators.</p>
            <p>Every piece of AI-generated content is labeled with an "AI Generated Summary" badge. You will always know when AI was used.</p>
          </Section>

          <Section title="What AI Does">
            <ul className="list-none flex flex-col gap-1">
              <Li>Summarizes government budgets, meeting minutes, contracts, and audits in plain English</Li>
              <Li>Explains ballot measures, tax proposals, bond issues, and constitutional amendments</Li>
              <Li>Generates "Explain Like I'm 12" summaries for complex topics</Li>
              <Li>Compares spending or activity between years and identifies large changes</Li>
              <Li>Assigns risk indicators (red flag, warning, or normal) based on detected changes</Li>
              <Li>Explains what a YES or NO vote means on ballot measures — without taking a position</Li>
            </ul>
          </Section>

          <Section title="What AI Does Not Do">
            <ul className="list-none flex flex-col gap-1">
              <Li>AI does not tell you who to vote for</Li>
              <Li>AI does not endorse any candidate, party, or ballot position</Li>
              <Li>AI does not make legal, financial, or political judgments</Li>
              <Li>AI does not replace official government records</Li>
              <Li>AI does not investigate or make accusations of wrongdoing</Li>
            </ul>
          </Section>

          <Section title="AI Limitations">
            <p>AI systems can make mistakes. Summaries may contain:</p>
            <ul className="list-none flex flex-col gap-1 mt-1">
              <Li>Factual inaccuracies or misinterpretations</Li>
              <Li>Omissions of important details</Li>
              <Li>Outdated information if the source document has changed</Li>
              <Li>Simplified or imprecise language</Li>
              <Li>Misidentified amounts, dates, or parties</Li>
            </ul>
          </Section>

          <Section title="Always Check the Source">
            <p>Every document in Small Town Watchdog includes a link to the official source. Before making any decision based on information in this app — especially involving voting, legal matters, or finances — always review the original government document.</p>
            <p>The official source document always takes precedence over any AI-generated summary or explanation.</p>
          </Section>

          <Section title="Neutral Stance on Elections">
            <p>Small Town Watchdog's AI is specifically configured to remain neutral on all election and ballot measure content. AI is instructed to explain what each side of a vote means without recommending how to vote. No language in AI-generated election content should be interpreted as an endorsement or recommendation.</p>
          </Section>

          <Section title="Red Flag Indicators">
            <p>Red flag and warning indicators are generated by automated comparison of government data — not by human investigators. A red flag means an unusually large change was detected. It does not mean wrongdoing occurred. Always review the original source before drawing conclusions.</p>
          </Section>

          <Section title="Reporting Problems">
            <p>If you believe an AI-generated summary contains a significant error or is misleading, please contact us. We take content accuracy seriously and will review reported issues.</p>
          </Section>

        </Card>
      </div>
    </AppLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-2 border-t border-border/50 pt-4 first:border-0 first:pt-0">
      <h2 className="text-sm font-bold uppercase tracking-wider text-primary">{title}</h2>
      <div className="flex flex-col gap-2 text-muted-foreground leading-relaxed">{children}</div>
    </div>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <span className="text-primary font-bold shrink-0 mt-0.5">·</span>
      <span>{children}</span>
    </li>
  );
}
