import { Router, type IRouter } from "express";
import healthRouter from "./health";
import entitiesRouter from "./entities";
import sourcesRouter from "./sources";
import documentsRouter from "./documents";
import alertsRouter from "./alerts";
import statsRouter from "./stats";
import compareRouter from "./compare";
import { electionsRouter } from "./elections";
import { ballotItemsRouter } from "./ballot-items";
import seedRouter from "./seed";
import sourceRegistryRouter from "./source-registry";
import sourceSubmissionsRouter from "./source-submissions";
import coverageRouter from "./coverage";
import validateSourcesRouter from "./validate-sources";
import locationsRouter from "./locations";
import civicItemsRouter from "./civic-items";
import errorReportsRouter from "./error-reports";
import diagnosticsRouter from "./diagnostics";
import exportRouter from "./export";
import emailSubscribersRouter from "./email-subscribers";
import civicItemFlagsRouter from "./civic-item-flags";
import remindersRouter from "./reminders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(entitiesRouter);
router.use(sourcesRouter);
router.use(documentsRouter);
router.use(validateSourcesRouter);
router.use(alertsRouter);
router.use(statsRouter);
router.use(compareRouter);
router.use("/elections", electionsRouter);
router.use("/ballot-items", ballotItemsRouter);
router.use(seedRouter);
router.use(sourceRegistryRouter);
router.use(sourceSubmissionsRouter);
router.use(coverageRouter);
router.use(locationsRouter);
router.use(civicItemsRouter);
router.use(errorReportsRouter);
router.use(diagnosticsRouter);
router.use(exportRouter);
router.use(emailSubscribersRouter);
router.use(civicItemFlagsRouter);
router.use(remindersRouter);

export default router;
